export const airlines = [
    ["BG", "Biman Bangladesh Airlines"],
    ["BS", "US-Bangla Airlines"],
    ["G9", "Air Arabia"],
    ["3L", "Air Arabia Abu Dhabi"],
    ["EK", "Emirates"],
    ["FZ", "flydubai"],
    ["EY", "Etihad Airways"],
    ["QR", "Qatar Airways"],
    ["SV", "Saudia"],
    ["XY", "Flynas"],
    ["F3", "flyadeal"],
    ["KU", "Kuwait Airways"],
    ["J9", "Jazeera Airways"],
    ["GF", "Gulf Air"],
    ["WY", "Oman Air"],
    ["OV", "SalamAir"],
    ["TK", "Turkish Airlines"],
    ["AI", "Air India"],
    ["6E", "IndiGo"],
    ["MH", "Malaysia Airlines"],
    ["OD", "Batik Air"],
    ["AK", "AirAsia"],
    ["SQ", "Singapore Airlines"],
    ["TG", "Thai Airways"],
    ["FD", "Thai AirAsia"],
    ["UL", "SriLankan Airlines"],
    ["8D", "FitsAir"],
    ["CZ", "China Southern Airlines"],
    ["MU", "China Eastern Airlines"],
    ["CA", "Air China"],
    ["CX", "Cathay Pacific"],
    ["H9", "Himalaya Airlines"],
    ["KB", "Drukair"],
    ["Q2", "Maldivian"],
    ["ET", "Ethiopian Airlines"],
    ["MS", "EgyptAir"],
    ["LJ", "Jin Air"],
    ["YP", "Air Premia"],
    ["OTHER", "Other Airline"],
] as const;